version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: movielens-fastapi
    ports:
      - "8000:8000"
    environment:
      MOVIELENS_DATA_DIR: /data/ml-32m
      MOVIELENS_ARTIFACT_PATH: /app/artifacts/movielens_runtime.joblib
      MOVIELENS_RUNTIME_MODE: artifact
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
    restart: unless-stopped
